# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# puts "HIHIHIHI"
# Tile.all.map { |tile| tile.update_attribute( :click_count, tile.tile_clicks.count ) }
# Tile.create!([{string: "1 Maraschino Short of Fruitcake"},
# 							{string: "A Room Without a Roof"},
# 							{string: "A Very Scummy Christmas!"},
# 							{string: "Angry Elf"},
# 							{string: "Antiquated System"},
# 							{string: "Bag Lady"},
# 							{string: "Basan"},
# 							{string: "Blackbird"},
# 							{string: "Blitzen"},
# 							{string: "Bob (the gnome) Sledder"},
# 							{string: "Bowies Laughing Gnome"},
# 							{string: "Broody Bantams"},
# 							{string: "Christmas Balls"},
# 							{string: "Cindy Lou Who"},
# 							{string: "Cornucopious"},
# 							{string: "Currier & Ives"},
# 							{string: "Don't Hate Me Cuz I'm Pretty!"},
# 							{string: "Dreidel"},
# 							{string: "Electric Kool-Aid Acid Test"},
# 							{string: "Farmhouse"},
# 							{string: "Festivus"},
# 							{string: "Fire on the Mountain"},
# 							{string: "Fleece Navidad"},
# 							{string: "FrankenHen"},
# 							{string: "Free Range Chickens"},
# 							{string: "Fungus Among US"},
# 							{string: "Gail's Autumn Joy"},
# 							{string: "Gandalf the Grey"},
# 							{string: "Gastropod Shuffle"},
# 							{string: "Ghoulash"},
# 							{string: "Ginger Plum-licious"},
# 							{string: "Gnome de Plume"},
# 							{string: "Gnome for the Holidays"},
# 							{string: "Go Beavs!"},
# 							{string: "Grimm"},
# 							{string: "H2O Yeah"},
# 							{string: "Hangin' with my Gnomies"},
# 							{string: "Hearth and Gnome"},
# 							{string: "Heirloomed"},
# 							{string: "Hobbit Garden"},
# 							{string: "Holiday Hen"},
# 							{string: "Holiday Inn"},
# 							{string: "Holly and Ivy"},
# 							{string: "Holly no Berry"},
# 							{string: "Hollyday"},
# 							{string: "I'm Too Sexy for Your Needles"},
# 							{string: "Jabberwocky"},
# 							{string: "Joy to the World"},
# 							{string: "Just Jack!"},
# 							{string: "KaPOW PaTINA"},
# 							{string: "Kokopelli"},
# 							{string: "Lake Crescent"},
# 							{string: "Maize"},
# 							{string: "Marisol's Flue"},
# 							{string: "Monroe Blutbad"},
# 							{string: "Mossely Manly"},
# 							{string: "Muddy Autumn Rainbow"},
# 							{string: "Oaks Bottom"},
# 							{string: "Obsidian"},
# 							{string: "Penguins on Ice"},
# 							{string: "Portland Plaid"},
# 							{string: "Princess Plummy"},
# 							{string: "Purple Phantom"},
# 							{string: "Rainbow Reindeer"},
# 							{string: "River Rocked"},
# 							{string: "Rooster Rocked"},
# 							{string: "Rosalee Fuchsbau"},
# 							{string: "Royal"},
# 							{string: "Samhain"},
# 							{string: "Sapphire"},
# 							{string: "Sea Scum, Sea Scum Run"},
# 							{string: "Smokey Mountain Morn"},
# 							{string: "Stardust"},
# 							{string: "StinkEYE"},
# 							{string: "Strange Brew"},
# 							{string: "Supercolourfragilistic"},
# 							{string: "Tea and Alchemy"},
# 							{string: "The Gnome of Christmas Present"},
# 							{string: "The Kracken"},
# 							{string: "The Longest Night"},
# 							{string: "The Witching Hour"},
# 							{string: "Tina's Silver Lining"},
# 							{string: "Tinsel"},
# 							{string: "Tomatillo"},
# 							{string: "Tulgey Woods"},
# 							{string: "Turquoise"},
# 							{string: "Under the Mistletoe"},
# 							{string: "Watch Where The Huskies Go..."},
# 							{string: "Watermelon Tourmaline"},
# 							{string: "Who's the Pumpkin?"},
# 							{string: "WhoVille"},
# 							{string: "Witchy Woman"},
# 							{string: "Yuletide"}
# 							])
